name: Build Geode Mod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: ubuntu-latest
            target: Android32
          - os: ubuntu-latest
            target: Android64

    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: geode-sdk/build-geode-mod@main
        with:
          sdk: nightly
          target: ${{ matrix.config.target }}
